---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  custom_pre_install_command: 'sudo yum install -y docker'
  manifests_path: spec/acceptance/examples
  hiera_config_path: spec/acceptance/hiera.yaml
  hiera_data_path: spec/acceptance/hieradata
  hiera_data_remote_path: /etc/puppet/hieradata
  ignore_spec_fixtures: true
  require_chef_for_busser: false
  custom_facts:
    aws_api_key: <%= ENV['AWS_ACCESS_KEY_ID']%>
    aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY']%>

transport:
  name: sftp

platforms:
  - name: centos-7.4

verifier:
  name: serverspec
  remote_exec: false
  extra_flags: '--require spec_helper -I spec/acceptance'

suites:
  - name: default
    provisioner:
      manifest: init.pp
    verifier:
      patterns:
        - 'spec/acceptance/**_spec.rb'
